# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 'https://trevor-mill.github.io/'
baseurl:             'learning_journal/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Trevor Million
  url:               
  email:             trevor.million@chicagobooth.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
